### ISSUE TITLE
Fix Genesis Block

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/dune-sync#31]
https://github.com/cowprotocol/dune-sync/blob/2d4cc5c28d2e50d4dc2607629d281ed3329462b9/src/sync/order_rewards.py#L90-L91

When ready we should set the first sync block for this script. Doesn't matter if its super accurate since we won't use earlier blocks. But it should start from a point we know the data is correct.

**Comment by sunce86** [comment]
Yes, IIUC we can set any block right now because the db tables used for batch rewards are already populated with data.

**Comment by bh2smith** [comment]
> which at the time I am writing this msg, is roughly (a few minutes back)
https://etherscan.io/block/16862919

The block needs to be before last Tuesday if we are planning to do a trial run this week...

**Comment by bh2smith** [comment]
However, if we are fine not having the data in Dune for the week of the trial run, then we can proceed with this suggested block number.
